from __future__ import annotations

from app.services.marketplaces.base import MarketplaceProduct


DEMO_PRODUCTS_BY_PROJECT = {
    "uyut-za-kopeiki": [
        MarketplaceProduct(
            source="wb",
            source_id="home-1",
            title="Постельное белье сатин 2-спальное",
            brand="SoftNest",
            category="bedding",
            price=2890,
            market_price=3990,
            discount_percent=28,
            rating=4.9,
            reviews_count=842,
            stock_count=24,
            url="https://example.com/home-1",
            description="Нежный комплект для спокойной спальни.",
            characteristics={"fabric": "сатин", "size": "2-спальное"},
            images=["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85"],
        ),
        MarketplaceProduct(
            source="ozon",
            source_id="home-2",
            title="Настольная лампа с тёплым светом",
            brand="WarmLight",
            category="lamps",
            price=1790,
            market_price=2490,
            discount_percent=28,
            rating=4.8,
            reviews_count=312,
            stock_count=17,
            url="https://example.com/home-2",
            description="Лампа для уютного рабочего стола или спальни.",
            characteristics={"light": "warm", "power": "8W"},
            images=["https://images.unsplash.com/photo-1513694203232-719a280e022f"],
        ),
        MarketplaceProduct(
            source="ym",
            source_id="home-3",
            title="Набор кухонных органайзеров",
            brand="Orderly",
            category="organizers",
            price=990,
            market_price=1490,
            discount_percent=33,
            rating=4.7,
            reviews_count=144,
            stock_count=55,
            url="https://example.com/home-3",
            description="Помогает навести порядок на кухне и в шкафах.",
            characteristics={"set": "3 pcs", "material": "plastic"},
            images=["https://images.unsplash.com/photo-1556911220-bff31c812dba"],
        ),
    ],
    "zheleznyi-vitamin": [
        MarketplaceProduct(
            source="wb",
            source_id="fit-1",
            title="Сывороточный протеин 1 кг",
            brand="PureFuel",
            category="protein",
            price=2290,
            market_price=3290,
            discount_percent=30,
            rating=4.9,
            reviews_count=1203,
            stock_count=41,
            url="https://example.com/fit-1",
            description="Базовый протеин на каждый день.",
            characteristics={"protein": "whey", "weight": "1kg"},
            images=["https://images.unsplash.com/photo-1517836357463-d25dfeac3438"],
        ),
        MarketplaceProduct(
            source="ozon",
            source_id="fit-2",
            title="Креатин моногидрат 300 г",
            brand="PowerLab",
            category="creatine",
            price=1190,
            market_price=1690,
            discount_percent=29,
            rating=4.8,
            reviews_count=508,
            stock_count=67,
            url="https://example.com/fit-2",
            description="Популярная добавка для силовых тренировок.",
            characteristics={"form": "monohydrate", "weight": "300g"},
            images=["https://images.unsplash.com/photo-1594737625785-a6cbdabd333c"],
        ),
        MarketplaceProduct(
            source="ym",
            source_id="fit-3",
            title="Омега-3 90 капсул",
            brand="NutriCore",
            category="omega-3",
            price=890,
            market_price=1290,
            discount_percent=31,
            rating=4.8,
            reviews_count=224,
            stock_count=88,
            url="https://example.com/fit-3",
            description="Омега для ежедневного рациона.",
            characteristics={"capsules": 90},
            images=["https://images.unsplash.com/photo-1550572017-edd951aa8ca3"],
        ),
    ],
    "tochka-stilyev": [
        MarketplaceProduct(
            source="wb",
            source_id="style-1",
            title="Nike Air Force 1 low",
            brand="Nike",
            category="sneakers",
            price=7990,
            market_price=9990,
            discount_percent=20,
            rating=4.9,
            reviews_count=421,
            stock_count=19,
            url="https://example.com/style-1",
            description="Классика, которая почти всегда уместна в гардеробе.",
            characteristics={"model": "Air Force 1", "type": "original"},
            images=["https://images.unsplash.com/photo-1542291026-7eec264c27ff"],
        ),
        MarketplaceProduct(
            source="ozon",
            source_id="style-2",
            title="Худи oversize streetwear",
            brand="UrbanLine",
            category="apparel",
            price=2490,
            market_price=3490,
            discount_percent=28,
            rating=4.7,
            reviews_count=188,
            stock_count=37,
            url="https://example.com/style-2",
            description="Базовое худи для повседневного образа.",
            characteristics={"fit": "oversize", "style": "streetwear"},
            images=["https://images.unsplash.com/photo-1523398002811-999ca8dec234"],
        ),
        MarketplaceProduct(
            source="ym",
            source_id="style-3",
            title="Кепка с минималистичным логотипом",
            brand="Mono",
            category="streetwear",
            price=1190,
            market_price=1690,
            discount_percent=29,
            rating=4.6,
            reviews_count=92,
            stock_count=63,
            url="https://example.com/style-3",
            description="Простой аксессуар, который собирает образ.",
            characteristics={"type": "cap", "style": "minimal"},
            images=["https://images.unsplash.com/photo-1523398002811-999ca8dec234"],
        ),
    ],
    "techno-halava": [
        MarketplaceProduct(
            source="ozon",
            source_id="tech-1",
            title="Механическая клавиатура 75% RGB",
            brand="KeyNova",
            category="keyboards",
            price=3990,
            market_price=5990,
            discount_percent=33,
            rating=4.8,
            reviews_count=1264,
            stock_count=31,
            url="https://example.com/tech-1",
            description="Компактная механическая клавиатура с RGB-подсветкой.",
            characteristics={"layout": "75%", "switches": "linear"},
            images=["https://images.unsplash.com/photo-1541140532154-b024d705b90a"],
        ),
        MarketplaceProduct(
            source="wildberries",
            source_id="tech-2",
            title="Игровая мышь 24000 DPI",
            brand="ProClick",
            category="mice",
            price=1890,
            market_price=2590,
            discount_percent=27,
            rating=4.7,
            reviews_count=342,
            stock_count=58,
            url="https://example.com/tech-2",
            description="Лёгкая игровая мышь с настраиваемой подсветкой.",
            characteristics={"dpi": "24000", "buttons": 8},
            images=["https://images.unsplash.com/photo-1527814050087-3793815479db"],
        ),
        MarketplaceProduct(
            source="yandex_market",
            source_id="tech-3",
            title='Монитор 27" IPS 165 Гц',
            brand="ViewPro",
            category="monitors",
            price=14990,
            market_price=18990,
            discount_percent=21,
            rating=4.9,
            reviews_count=89,
            stock_count=12,
            url="https://example.com/tech-3",
            description="Монитор для работы и игр с тонкими рамками.",
            characteristics={"resolution": "2560x1440", "refresh_rate": "165Hz"},
            images=["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf"],
        ),
    ],
}


def get_demo_products(project_slug: str) -> list[MarketplaceProduct]:
    return DEMO_PRODUCTS_BY_PROJECT.get(project_slug, DEMO_PRODUCTS_BY_PROJECT["techno-halava"])

